### ISSUE TITLE
Giff wiki pls

### ISSUE THREAD

**Issue by jimmydorry** [GetDotaStats/stat-highscore#1]
Pls ![CryingMan](http://dota2.photography/public/s/BibleThump.png)

**Comment by ash47** [comment]
Never.

**Comment by ash47** [comment]
;)

**Comment by jimmydorry** [comment]
We came so close, but are so far away. The rpg library has the complete set of code and documentation, even though I still need to fix some server sided stuff to lock it down to prevent obvious abuse.

Highscores are fully functional, and have been for a while but lack the documentation.

![CryingMan](http://dota2.photography/public/s/BibleThump.png)

**Comment by jimmydorry** [comment]
Thanks @mnoya
